
import java.util.Date;

 import net.sourceforge.jFuzzyLogic.*;
import net.sourceforge.jFuzzyLogic.defuzzifier.Defuzzifier;
import net.sourceforge.jFuzzyLogic.plot.JFuzzyChart;
import net.sourceforge.jFuzzyLogic.rule.Variable;
import java.util.Random;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Faisal
 */
public class Simulasi extends javax.swing.JFrame {

     //To change body of generated methods, choose Tools | Templates.
    
    
               
         Random rand= new Random();
         double randsuhuSM=(-4) + ((-1) - (-4)) * rand.nextDouble();
         double randlembabSM=(-10) + ((10) - (-10)) * rand.nextDouble();
         double randanginSM=(-4) + ((4) - (-4)) * rand.nextDouble();
         double randsuhuPS=(1) + ((6) - (1)) * rand.nextDouble();
         double randlembabPS=(-10) + ((6) - (-10)) * rand.nextDouble();
         double randanginPS=(-5) + ((6) - (-5)) * rand.nextDouble();
         
String fileName = "C:\\Users\\RetDev\\Desktop\\PERANCANGAN SISTEM PERAMALAN CUACA BERBASIS LOGIKA FUZZY\\Source Code\\Simulasi\\src\\tipper.fcl";
        FIS fis = FIS.load(fileName,true);
        Date d=new Date();
 String waktu;
        int dd=d.getHours();
        String jam= String.valueOf(dd);
      
        
    /**
     * Creates new form Simulasi
     */
    
    public Simulasi() {
        initComponents();
 setResizable(false);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Suhu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        showsuhu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Kelembaban = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Angin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        showan = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        showlem = new javax.swing.JLabel();
        Pagi = new javax.swing.JRadioButton();
        Siang = new javax.swing.JRadioButton();
        Malam = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulasi Prediksi Cuaca Hari Ini");
        setBackground(new java.awt.Color(0, 102, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(85, 184, 233));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 900));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 900));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadow2.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabel7.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel1.setText("Suhu");

        jLabel4.setText(":");

        jLabel8.setText("Prediksi suhu");

        showsuhu.setText("suhu");

        jLabel9.setText("prediksi kelembaban");

        jLabel2.setText("Kelembaban");

        jLabel5.setText(":");

        jLabel3.setText("Angin");

        jLabel6.setText(":");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        showan.setText("jLabel8");

        jLabel10.setText("prediksi angin");

        showlem.setText("jLabel8");

        buttonGroup1.add(Pagi);
        Pagi.setText("Pag(03.00-10.59)");
        Pagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagiActionPerformed(evt);
            }
        });

        buttonGroup1.add(Siang);
        Siang.setText("Siang (11.00-16.59)");
        Siang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiangActionPerformed(evt);
            }
        });

        buttonGroup1.add(Malam);
        Malam.setText("Malam(17.00-02.59)");
        Malam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalamActionPerformed(evt);
            }
        });

        jLabel11.setText("°C");

        jLabel12.setText("%");

        jLabel13.setText("KM/Jam");

        jLabel14.setText("KM/Jam");

        jLabel15.setText("%");

        jLabel16.setText("°C");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pagi)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Suhu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(Kelembaban, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(showan)
                                    .addComponent(showlem)
                                    .addComponent(showsuhu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Angin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jButton1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Siang)
                        .addGap(28, 28, 28)
                        .addComponent(Malam)))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)
                        .addComponent(Suhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(Kelembaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Angin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel3)
                        .addComponent(jButton1)
                        .addComponent(jLabel13)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(showsuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(showlem)
                    .addComponent(jLabel15))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(showan)
                    .addComponent(jLabel14))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pagi)
                    .addComponent(Siang)
                    .addComponent(Malam))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MalamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalamActionPerformed
        Malam.isSelected();
        if("pagi".equals(waktu)){
            double suhupagi= Double.parseDouble(Suhu.getText());
            double kelembabanpagi= Double.parseDouble(Kelembaban.getText());
            double anginpagi= Double.parseDouble(Angin.getText());

            if(Double.parseDouble(Angin.getText())<5){
                randanginPS=(-1*(Double.parseDouble(Angin.getText()))) + ((6) - (-1*Double.parseDouble(Angin.getText()))) * rand.nextDouble();
            }
            if(Double.parseDouble(Kelembaban.getText())<10){
                randlembabPS=(-1*Double.parseDouble(Kelembaban.getText())) + ((6) - (-1*Double.parseDouble(Kelembaban.getText()))) * rand.nextDouble();
            }

            double suhusiang= suhupagi+(randsuhuPS);
            double kelembabansiang= kelembabanpagi+(randlembabPS);
            double anginsiang= anginpagi+(randanginPS);

            if(anginsiang<4){
                randanginSM=(-1*anginsiang) + ((4) - (-1*(anginsiang))) * rand.nextDouble();
            }
            if(Double.parseDouble(Kelembaban.getText())<10){
                randlembabSM=(-1*kelembabansiang) + ((6) - (-1*kelembabansiang)) * rand.nextDouble();
            }
            double suhumalam=suhusiang+(randsuhuSM);
            double kelembabanmalam=kelembabansiang+(randlembabSM);
            double anginmalam=anginsiang+(randanginSM);
            double g=0,h=0;
            int m=0,i;

            fis.setVariable("suhu", suhumalam);
            fis.setVariable("kelembaban", kelembabanmalam);
            fis.setVariable("angin", anginmalam);
            fis.evaluate();

            for(i=0;i<27;i++){
                if(fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport()>0){
                    System.out.println(fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i));
                    h=fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport();
                    if(h>g){
                        g=fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport();

                        m=i+1;

                    }

                }
            }
            if(m==1||m==2||m==3||m==4||m==7||m==8||m==10||m==11||m==19){
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowhuj.gif"))); // NOI18N

            }
            else if(m==5||m==6||m==9||m==12||m==13||m==14||m==16||m==20||m==23){
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowmen.jpg"))); // NOI18N

            }
            else{    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowcer.gif"))); // NOI18N
            }

            showsuhu.setText(String.valueOf(suhumalam));
            showlem.setText(String.valueOf(kelembabanmalam));
            showan.setText(String.valueOf(anginmalam));

        }

        if("siang".equals(waktu)){
            double g=0,h=0;
            int m=0,i;

            double suhusiang= Double.parseDouble(Suhu.getText());
            double kelembabansiang= Double.parseDouble(Kelembaban.getText());
            double anginsiang= Double.parseDouble(Angin.getText());
            if(anginsiang<4){
                randanginSM=(-1*anginsiang) + ((4) - (-1*anginsiang)) * rand.nextDouble();
            }
            if(Double.parseDouble(Kelembaban.getText())<10){
                randlembabSM=(-1*Double.parseDouble(Kelembaban.getText())) + ((6) - (-1*Double.parseDouble(Kelembaban.getText()))) * rand.nextDouble();
            }
            double suhumalam=suhusiang+(randsuhuSM);
            double kelembabanmalam=kelembabansiang+(randlembabSM);
            double anginmalam=anginsiang+(randanginSM);
            fis.setVariable("suhu", suhumalam);
            fis.setVariable("kelembaban", kelembabanmalam);
            fis.setVariable("angin", anginmalam);
            fis.evaluate();

            for(i=0;i<27;i++){
                if(fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport()>0){
                    System.out.println(fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i));
                    h=fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport();
                    if(h>g){
                        g=fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport();

                        m=i+1;

                    }

                }
            }
            if(m==1||m==2||m==3||m==4||m==7||m==8||m==10||m==11||m==19){
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowhuj.gif"))); // NOI18N

            }
            else if(m==5||m==6||m==9||m==12||m==13||m==14||m==16||m==20||m==23){
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowmen.jpg"))); // NOI18N

            }
            else{    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowcer.gif"))); // NOI18N
            }
            Variable besok = fis.getVariable("prediksi");JFuzzyChart.get().chart(fis);

            showsuhu.setText(String.valueOf(suhumalam));
            showlem.setText(String.valueOf(kelembabanmalam));
            showan.setText(String.valueOf(anginmalam));

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_MalamActionPerformed

    private void SiangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiangActionPerformed

        if("siang".equals(waktu)){
            double g=0,h=0;
            int m=0,i;

            if(Double.parseDouble(Angin.getText())<4){
                randanginSM=(-1*(Double.parseDouble(Angin.getText()))) + ((4) - (-1*(Double.parseDouble(Angin.getText())))) * rand.nextDouble();
            }
            if(Double.parseDouble(Kelembaban.getText())<10){
                randlembabSM=(-1*Double.parseDouble(Kelembaban.getText())) + ((6) - (-1*Double.parseDouble(Kelembaban.getText()))) * rand.nextDouble();
            }

            double suhusiang= Double.parseDouble(Suhu.getText());
            double kelembabansiang= Double.parseDouble(Kelembaban.getText());
            double anginsiang= Double.parseDouble(Angin.getText());
            double suhumalam=suhusiang+(randsuhuSM);
            double kelembabanmalam=kelembabansiang+(randlembabSM);
            double anginmalam=anginsiang+(randanginSM);
            fis.setVariable("suhu", suhusiang);
            fis.setVariable("kelembaban", kelembabansiang);
            fis.setVariable("angin", anginsiang);
            fis.evaluate();

            for(i=0;i<27;i++){
                if(fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport()>0){
                    System.out.println(fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i));
                    h=fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport();
                    if(h>g){
                        g=fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport();

                        m=i+1;

                    }

                }
            }
            if(m==1||m==2||m==3||m==4||m==7||m==8||m==10||m==11||m==19){
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowhuj.gif"))); // NOI18N

            }
            else if(m==5||m==6||m==9||m==12||m==13||m==14||m==16||m==20||m==23){
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowmen.jpg"))); // NOI18N

            }
            else{    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowcer.gif"))); // NOI18N
            }
            Variable besok = fis.getVariable("prediksi");JFuzzyChart.get().chart(fis);

            showsuhu.setText(String.valueOf(suhusiang));
            showlem.setText(String.valueOf(kelembabansiang));
            showan.setText(String.valueOf(anginsiang));

        }

        /*fuzzy siang*/

        if("pagi".equals(waktu)){
            if(Double.parseDouble(Angin.getText())<5){
                randanginPS=(-1*(Double.parseDouble(Angin.getText()))) + ((6) - (-1*Double.parseDouble(Angin.getText()))) * rand.nextDouble();
            }
            if(Double.parseDouble(Kelembaban.getText())<10){
                randlembabPS=(-1*Double.parseDouble(Kelembaban.getText())) + ((6) - (-1*Double.parseDouble(Kelembaban.getText()))) * rand.nextDouble();
            }
            double suhupagi= Double.parseDouble(Suhu.getText());
            double kelembabanpagi= Double.parseDouble(Kelembaban.getText());
            double anginpagi= Double.parseDouble(Angin.getText());
            double suhusiang= suhupagi+(randsuhuPS);
            double kelembabansiang= kelembabanpagi+(randlembabPS);
            double anginsiang= anginpagi+(randanginPS);
            double g=0,h=0;
            int m=0,i;

            fis.setVariable("suhu", suhusiang);
            fis.setVariable("kelembaban", kelembabansiang);
            fis.setVariable("angin", anginsiang);
            fis.evaluate();

            for(i=0;i<27;i++){
                if(fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport()>0){
                    System.out.println(fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i));
                    h=fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport();
                    if(h>g){
                        g=fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport();

                        m=i+1;

                    }

                }
            }
            if(m==1||m==2||m==3||m==4||m==7||m==8||m==10||m==11||m==19){
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowhuj.gif"))); // NOI18N

            }
            else if(m==5||m==6||m==9||m==12||m==13||m==14||m==16||m==20||m==23){
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowmen.jpg"))); // NOI18N

            }
            else{    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowcer.gif"))); // NOI18N
            }
            Variable besok = fis.getVariable("prediksi");
            JFuzzyChart.get().chart(fis);

            showsuhu.setText(String.valueOf(suhusiang));
            showlem.setText(String.valueOf(kelembabansiang));
            showan.setText(String.valueOf(anginsiang));
        }
        /*fuzzy siang*/
        // TODO add your handling code here:
    }//GEN-LAST:event_SiangActionPerformed

    private void PagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagiActionPerformed
        Pagi.isSelected();

        if("pagi".equals(waktu)){
            double suhupagi= Double.parseDouble(Suhu.getText());
            double kelembabanpagi= Double.parseDouble(Kelembaban.getText());
            double anginpagi= Double.parseDouble(Angin.getText());

            fis.setVariable("suhu", suhupagi);
            fis.setVariable("kelembaban", kelembabanpagi);
            fis.setVariable("angin", anginpagi);
            fis.evaluate();

            showsuhu.setText(String.valueOf(suhupagi));
            showlem.setText(String.valueOf(kelembabanpagi));
            showan.setText(String.valueOf(anginpagi));
            double g=0,h=0;
            int m=0,i;

            for(i=0;i<27;i++){
                if(fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport()>0){
                    System.out.println(fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i));
                    h=fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport();
                    if(h>g){
                        g=fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport();

                        m=i+1;

                    }

                }
            }
            if(m==1||m==2||m==3||m==4||m==7||m==8||m==10||m==11||m==19){
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowhuj.gif")));

            }
            else if(m==5||m==6||m==9||m==12||m==13||m==14||m==16||m==20||m==23){
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowmen.jpg")));

            }
            else{    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowcer.gif")));
            }
            Variable besok = fis.getVariable("prediksi");
            JFuzzyChart.get().chart(fis);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_PagiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(Double.parseDouble(Kelembaban.getText())<0||Double.parseDouble(Angin.getText())<0){
            JOptionPane.showMessageDialog(rootPane, "Input Error");

        }
        else{
            if(dd>2&&dd<11){
                waktu="pagi";
                Pagi.doClick();

            }

            else if(dd>=11&&dd<=16){
                waktu="siang";
                Siang.doClick();
                Pagi.hide();

            }

            else{
                waktu="malam";

                Malam.doClick();
                Siang.hide();
                Pagi.hide();
                double suhu= Double.parseDouble(Suhu.getText());
                double kelembaban= Double.parseDouble(Kelembaban.getText());
                double angin= Double.parseDouble(Angin.getText());
                double g=0,h=0;
                int m=0,i;

                /*fuzzy*/
                fis.setVariable("suhu", suhu);
                fis.setVariable("kelembaban", kelembaban);
                fis.setVariable("angin", angin);
                fis.evaluate();

                /*fuzzy*/

                for(i=0;i<27;i++){
                    if(fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport()>0){
                        System.out.println(fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i));
                        h=fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport();
                        if(h>g){
                            g=fis.getFunctionBlock("tipper").getFuzzyRuleBlock("No1").getRules().get(i).getDegreeOfSupport();

                            m=i+1;

                        }

                    }
                }
                if(m==1||m==2||m==3||m==4||m==7||m==8||m==10||m==11||m==19){
                    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowhuj.gif"))); // NOI18N

                }
                else if(m==5||m==6||m==9||m==12||m==13||m==14||m==16||m==20||m==23){
                    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowmen.jpg"))); // NOI18N

                }
                else{    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipushadowcer.gif"))); // NOI18N
                }

                showsuhu.setText(String.valueOf(suhu));
                showlem.setText(String.valueOf(kelembaban));
                showan.setText(String.valueOf(angin));

                Variable besok = fis.getVariable("prediksi");
                JFuzzyChart.get().chart(fis);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulasi().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Angin;
    private javax.swing.JTextField Kelembaban;
    private javax.swing.JRadioButton Malam;
    private javax.swing.JRadioButton Pagi;
    private javax.swing.JRadioButton Siang;
    private javax.swing.JTextField Suhu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel showan;
    private javax.swing.JLabel showlem;
    private javax.swing.JLabel showsuhu;
    // End of variables declaration//GEN-END:variables

    private String chart(Variable besok, Defuzzifier defuzzifier) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
